### ISSUE TITLE
API Composition and TypeScript

### ISSUE THREAD

**Issue by Gu3** [vuex-orm/vuex-orm-next#41]
Hi ! 
First of all : awesome project ! 
Do you have any tips to include vuex-orm-next with api composition and typescript ? 

I saw an old issue : 

`import { useRepo } from '@vuex-orm/core'
import User from '@/models/User'

export default {
  setup() {
    const useRepo = useRepo(User)
  }
}`

Any news about this ? 
Thank you !

**Comment by jfarraraains** [comment]
I just came looking at the same thing. I am wanting TypeScript support.

**Comment by Gu3** [comment]
If you are on Nuxt you can try the nuxtjs/composition-api and then : 

const { store } = useContext()
const accessesRepo = ref(store.$repo(Access))

**Comment by aranoe** [comment]
Essentially, migrating from Vue 2 to Vue 3 would probably make it possible to stitch the whole vuex dependency, since Vue's Composition API is [powerful enough](https://www.google.com/search?q=do+we+need+vuex+in+vue+3&rlz=1C5CHFA_enDE929DE929&oq=do+we+need+vuex+in+vue+3&aqs=chrome..69i57.4335j0j7&sourceid=chrome&ie=UTF-8).

**Comment by cuebit** [comment]
> If you are on Nuxt you can try the nuxtjs/composition-api and then : 
> 
> const { store } = useContext()
> 
> const accessesRepo = ref(store.$repo(Access))

Never use ref. Always use computed. 

```ts
const accessRepo = store.$repo(Access)

const items = computed(() => accessRepo.all())
```

And yes the library has TS support, considering it's built using TS.

There will be a VCA example repo soon. 👍

**Comment by kiaking** [comment]
I guess the question is solved 👀  Closing it for now!
